language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer --prefer-source --dev install
  - wget https://phar.phpunit.de/phpcov.phar
  - mkdir -p /tmp/tests/ThriftGenerator

script: ./vendor/bin/phpunit --coverage-clover=/tmp/tests/ThriftGenerator/coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover /tmp/tests/ThriftGenerator/coverage.clover

git:
  depth: 5